add inner page template
js-tasks-ru/htmlcss-20230911-4_kolva-alena pull request #10
Opened 2023-09-29 07:58 UTC by OlenaShkurenko

2023-09-29 07:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-29 08:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-29 08:19 UTC, GSemikozov requested changes

2023-09-29 08:19 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__title_inner {
лучше подвязываться под один общий модификатор состояния блока - .footer_inner .footer__title {}

2023-09-29 08:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-01 19:35 UTC, GSemikozov approved these changes

2023-10-01 19:35 UTC, merged