Svg sprites
js-tasks-ru/htmlcss-20230911-4_kolva-alena pull request #15
Opened 2023-10-04 20:11 UTC by OlenaShkurenko

2023-10-04 20:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-04 21:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-05 20:31 UTC, GSemikozov requested changes

2023-10-05 20:31 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.arrow-icon {
.accordion__arrow

2023-10-05 20:31 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  right: 32px;
сверху бы тоже указать явно

2023-10-05 20:31 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +  .arrow-icon {
вложенные селекторы как в sass? это не валидный код)

2023-10-06 19:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-06 19:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-06 20:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-10-07 21:31 UTC, GSemikozov approved these changes

2023-10-07 21:31 UTC, merged