add solution srcset
js-tasks-ru/htmlcss-20230911-4_kolva-alena pull request #18
Opened 2023-10-09 16:23 UTC by OlenaShkurenko

2023-10-09 16:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-10 20:19 UTC, GSemikozov requested changes

2023-10-10 20:19 UTC, GSemikozov commented on 06-lection4/03-srcset/index.html
> +        srcset="public/forest_400.jpg 1x"
в одном srcset, дублировать не надо: `srcset="public/forest_400.jpg 1x, public/forest_768.jpg 2x"`

2023-10-22 18:39 UTC, GSemikozov approved these changes

2023-10-22 18:39 UTC, merged