add solution checkbox
js-tasks-ru/htmlcss-20230911-4_kolva-alena pull request #19
Opened 2023-10-10 13:25 UTC by OlenaShkurenko

2023-10-10 20:23 UTC, GSemikozov requested changes

2023-10-10 20:23 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox-wrap {
такие врапперы = вспомогательные стили на уровне файла стилей блока мы не добавляем)
если хочется оставить - тогда в отдельном файле.

2023-10-10 20:23 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +  display: inline-flex;
и position: relative , чтобы абсолюты не вываливались за пределы блока

2023-10-10 20:23 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +  gap: 12px;
а это точно надо?

2023-10-10 20:23 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +  border-color: var(--grey-2);
и еще pointer-events: none

2023-10-10 20:23 UTC, GSemikozov commented on 07-lection5/01-checkbox/index.html
> +        <div class="checkbox">
вот здесь - label, тот который выше - лишний

2023-10-11 12:52 UTC, OlenaShkurenko commented on 07-lection5/01-checkbox/index.html
> +        <div class="checkbox">
Я не совсем поняла, почему лишник. он же обворачивает блок чекбокса и дает возможность нашему квадриту кликать на него + по тайтлу. (Как на лекции было обьяснено)
остальное поправила

2023-10-22 18:39 UTC, GSemikozov commented on 07-lection5/01-checkbox/index.html
> +        <div class="checkbox">
в том плане что сразу на него вешаем класс checkbox, а div удаляем)

2023-10-29 10:42 UTC, GSemikozov approved these changes

2023-10-29 10:42 UTC, merged