07-lection-toggler
js-tasks-ru/htmlcss-20230911-4_kolva-alena pull request #21
Opened 2023-10-10 14:16 UTC by OlenaShkurenko

2023-10-10 14:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-10 20:26 UTC, GSemikozov requested changes

2023-10-10 20:26 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.toggler-wrap {
см комменты по чекбоксу

2023-10-10 20:26 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +  text
тут и ниже какой-то мифический text затесался)

2023-10-10 20:26 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.toggler__title_switch{
1) модификатор сам по себе без того ЧТО он модифицируем использовать нельзя
2) но даже если это будет элемент блока - он все равно лишний, динамически текст менять не надо) а если надо - то проще через `content: 'on'`

2023-10-22 18:41 UTC, GSemikozov requested changes

2023-10-22 18:41 UTC, GSemikozov commented on 07-lection5/03-toggler/index.html
> +    <label>
см коммент по чекбоксу и радио

2023-10-29 10:44 UTC, GSemikozov approved these changes

2023-10-29 10:44 UTC, merged