add solution burger-menu
js-tasks-ru/htmlcss-20230911-4_kolva-alena pull request #24
Opened 2023-10-26 13:58 UTC by OlenaShkurenko

2023-10-26 14:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-10-29 10:49 UTC, GSemikozov requested changes

2023-10-29 10:49 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-logo {
это не самостоятельный блок, а элемент блока .burger-menu

2023-10-29 10:49 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +  max-width: 80%;
лишнее ограничение

2023-10-29 10:49 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +  max-width: 80%;
договаривались позиционировать блок через fixed и растягивать на весь вьюпорт

2023-10-29 10:49 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +.burger-logo {
а, по разметке вижу что это вообще самостоятельная кнопка, если хотим ее использовать в хедере, то тогда это элемент хедера

2023-11-01 14:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-07 11:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-13 15:13 UTC, GSemikozov approved these changes

2023-11-13 15:13 UTC, merged