add solution skeleton
js-tasks-ru/htmlcss-20230911-4_kolva-alena pull request #8
Opened 2023-09-25 08:36 UTC by OlenaShkurenko

2023-09-25 08:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-09-25 08:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-25 09:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-09-25 21:57 UTC, GSemikozov requested changes

2023-09-25 21:57 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__first-line {
отсюда и ниже - полное дублирование, верно? вот на этот случай нам и нужны модификаторы. Вместо того чтобы дублировать .skeleton__line который описан здесь, достаточно будет задать 4 модификатора - .skeleton__line_short и тд, где будем менять только ширину

2023-09-27 19:57 UTC, GSemikozov requested changes

2023-09-27 19:57 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  margin-bottom: 8px;
а если эта линия будет второй после той за которой следует сейчас?) отступы между элемента внутри флекс контейнера лучше задавать через gap

2023-09-27 19:57 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  margin-bottom: 8px;
и тут

2023-09-29 08:18 UTC, GSemikozov approved these changes

2023-09-29 08:18 UTC, merged